version: '3'

services:
  lidarr-album-monitor:
    build: .
    environment:
      - LIDARR_BASE_URL=${LIDARR_BASE_URL}
      - LIDARR_API_KEY=${LIDARR_API_KEY}
      - DAYS_TO_LOOK_BACK=${DAYS_TO_LOOK_BACK:-60}
