version: '3'

services:
  lidarr-album-monitor:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: lidarr-album-monitor-dev
    environment:
      - LIDARR_BASE_URL=${LIDARR_BASE_URL}
      - LIDARR_API_KEY=${LIDARR_API_KEY}
      - DAYS_TO_LOOK_BACK=${DAYS_TO_LOOK_BACK:-60}
      - INTERVAL_HOURS=${INTERVAL_HOURS:-24}
    restart: unless-stopped
    volumes:
      - ../src:/app/src
